### ISSUE TITLE
multithreading error in 1_detect_fused_gene.py

### ISSUE THREAD

**Issue by gdczoller** [wjidea/defusion#2]
Hi
I am testing deFusion and got below mulithreading error in the  1_detect_fused_gene.py  step. I am running this with python2.7.11. 
Would you happen to know what the problem is and how I can fix it? Thanks in advance!

```
(MainProcess) 2018-12-06 08:26:15,612 blastn is loaded in $PATH
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'Bio.Application.ApplicationError'>, ())

```

**Comment by jazberna1** [comment]
Hello,

I have the same error with python-2.7.9

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/software/python-2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/software/python-2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/software/python-2.7.9/lib/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'Bio.Application.ApplicationError'>, ())
`

Jorge

**Comment by wjidea** [comment]
I am going to look into this issue. Thank you for reporting this issue.

**Comment by wjidea** [comment]
I fixed the error in the most recent commit. Would you please try it again?  @jazberna1

**Comment by jazberna1** [comment]
Hello Jie,

This is the commit I have tried:

commit 0942525be8907b7b156cc963291c9d9537b4d503 (HEAD -> master, origin/master, origin/HEAD)
Author: Jie Wang <jwang7@lbl.gov>
Date:   Mon Dec 23 11:47:03 2019 -0800
add install tutorial with conda


However I still get the error:

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/software/python-2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/software/python-2.7.9/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/software/python-2.7.9/lib/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'Bio.Application.ApplicationError'>, ())`



Thanks
Jorge

**Comment by wjidea** [comment]
Yes, I checked it also with a bigger dataset. I can reproduce the error now.  I will look into it. Sorry for the inconvenience.

**Comment by jazberna1** [comment]
Hello Jie,

Thanks so much for looking into that. I would really appreciate if I could run your code over my Maker2 output.

Jorge

**Comment by wjidea** [comment]
Hi Jorge,
This error is associated with the multiprocessing part for parallel computing, which only happens in certain conditions, such as a bigger dataset in my test case. This might take me a while.

Jie

**Comment by ckeeling** [comment]
Hello Jie,

I am experiencing similar but not quite identical errors about multiprocessing. Any progress on this issue? You mention that it only seems to exist on bigger datasets. How small might we need to reduce the dataset (number of genome scaffolds, or evidence?) to avoid this error?

```bash
python ~/bin/defusion/defusion/1_detect_fused_gene.py -i transcripts.fa -g genome.gff -n 1 -p test_1 >testing_1.out 
(MainProcess) 2020-03-05 07:42:52,426 blastn is loaded in $PATH
Traceback (most recent call last):
  File "/home/ckeeling/bin/defusion/defusion/1_detect_fused_gene.py", line 394, in <module>
    main()
  File "/home/ckeeling/bin/defusion/defusion/1_detect_fused_gene.py", line 388, in main
    geneL = run_blast_parallel(seqFileL, prefixDir, numOfProcess, blastn, identityThreshold)
  File "/home/ckeeling/bin/defusion/defusion/1_detect_fused_gene.py", line 104, in run_blast_parallel
    fusedGeneL = pool.map(self_BLAST_partial, seqFileL)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: Option name max_hsps was not found.
```

At this point I am only doing a test, so I am setting n=1. Will have more cpus available for a real job.

Thanks,
Chris

**Comment by ckeeling** [comment]
Hi @wjidea 

Same error with 32 cpus.  "Option name max_hsps was not found" suggests it is something related to the blast search and bio.applications. Your installation instructions indicate BLAST+/2.2.30, which is ancient. Do you think your code will continue to work with a more recent release, such as BLAST 2.9.0+ that I am using? Any suggestions?

Thanks,
Chris

**Comment by ckeeling** [comment]
Hi @wjidea 

If I remove the ```max_hsps='10'``` from line 61 of 1_detect_fused_gene.py, I get the same error as @gdczoller originally posted.

**Comment by AFrolicOfFerns** [comment]
Hi everyone,

I'm getting the exact same error message first described above. Has anybody figured out what is going on here?

I've tried running with 1 and 30 cpus, with the following modules loaded. 
```
1) python/2.7.9        4) Biopython/1.65      7) MPICH2/1.5rc3      10) BioPerl/1.6.924    13) BLAST+/2.2.30      16) NumPy/1.13.1b
  2) OpenBLAS/0.2.13     5) BEDTools/2.29.2     8) trf/4.04           11) augustus/2.6.1     14) python/2.7.13      17) matplotlib/2.0.2b
  3) NumPy/1.13.1        6) gffutils/0.8.7.1b   9) fgenesh/3.1.2      12) MAKER/r1128        15) OpenBLAS/0.2.20    18) defusion/0.04
```

Here is my command:
```
1_detect_fused_gene.py -i $transcripts -g $maker_gff -n 30 --force --verbose -p deFusion
```

It looks like the 'seqs' directory is generated properly, then defusion appears to stall (still running, but not really using any cpus) until I kill it. 

Thanks!

**Comment by AFrolicOfFerns** [comment]
Nevermind! Everything seems to be working after I cloned defusion fresh from GitHub and re-ran.
